Repository Orion-Constellation-Organization/Backend, pull requests merged in 2024-10, with the labels that each got.

#1 Configuração inicial do repositório com ajustes para utilização do MySQL
  docker-compose.yml
  package-lock.json
  package.json
  src/app.ts
  src/config/database.ts
  src/config/swagger.ts
  tsconfig.json
Labels: configuration

#6 Fix: Change deprecated method + Database and api reconnection
  src/app.ts
  src/config/retryConnection.ts
  src/controller/TutorController.ts
  src/entity/EducationLevel.ts
  src/entity/LevelName.ts
  src/entity/Student.ts
  src/entity/Subject.ts
  src/entity/Tutor.ts
  src/entity/User.ts
Labels: bug

#7 feat: New endpoints for Student, Tutor and Education Level
  src/controller/EducationLevelController.ts
  src/controller/StudentController.ts
  src/controller/TutorController.ts
  src/routes.ts
  src/validator/StudentValidator.ts
  src/validator/TutorValidator.ts
Labels: feat

#10 feat: New entity lesson request, lesson request crontroller, subject controller
  src/controller/LessonRequestController.ts
  src/controller/SubjectController.ts
  src/entity/EducationLevel.ts
  src/entity/LessonRequest.ts
  src/entity/Student.ts
  src/entity/Subject.ts
  src/entity/enum/LevelName.ts
  src/entity/enum/ReasonName.ts
  src/entity/enum/StatusName.ts
  src/routes.ts
Labels: feat

#8 feat: add student validator + common validations
  src/controller/EducationLevelController.ts
  src/controller/StudentController.ts
  src/controller/TutorController.ts
  src/routes.ts
  src/validator/BaseValidator.ts
  src/validator/CommonValidations.ts
  src/validator/StudentValidator.ts
  src/validator/TutorValidator.ts
Labels: feat
